-- noinspection SqlNoDataSourceInspectionForFile
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c123','Skirt Party','50.0','20');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c456','Pants Party','20.0','10');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c789','Dress Party','90.0','20');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c111','Body (red)','30.5','100');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c222','Body (pink)','91.23','50');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c333','Jacket','39.99','190');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c444','Body Party','49.99','198');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c555','Jeans Slim','50.0','10');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c666','Jeans Mommy','112.99','12');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c777','Leader Jacket','199.99','67');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c888','Sockets','9.5','1000');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c999','Helmet','10.99','321');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c101','Summer Skirt','12.99','33');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c102','Summer Long Skirt','67.5','76');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c103','Summer Shorts (red)','87.0','25');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c104','Summer Shorts (blue)','99.0','5');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c105','Summer Shorts (jean)','29.0','167');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (nextval('hibernate_sequence'), 'c106','Winter Leader Shorts','30.0','18');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Tristan Infinispan','tristisispan@quarkus.io','+39 666','Italy');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Gunnar Debezium','gmorling@quarkus.io','+49 128','Germany');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Raphael Jovial','rjovial@quarkus.io','+33 661','France');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Adeline Insolite','ainsolite@quarkus.io','+33 662','France');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'William Fayot','wfayot@quarkus.io','+33 663','France');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Maria Rosario Frechilla','mfrechilla@quarkus.io','+34 221','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Aurea Stork','amunoz@quarkus.io','+34 222','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Laura Palmas','laura@quarkus.io','+34 223','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Felix Manager','fmanager@quarkus.io','+34 224','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (nextval('hibernate_sequence'), 'Igor Frere','ibrother@quarkus.io','+34 225','Spain');
