-- noinspection SqlNoDataSourceInspectionForFile
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (1, 'c123','Skirt Party','50.0','20');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (2, 'c456','Pants Party','20.0','10');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (3, 'c789','Dress Party','90.0','20');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (4, 'c111','Body (red)','30.5','100');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (5, 'c222','Body (pink)','91.23','50');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (6, 'c333','Jacket','39.99','190');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (7, 'c444','Body Party','49.99','198');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (8, 'c555','Jeans Slim','50.0','10');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (9, 'c666','Jeans Mommy','112.99','12');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (10, 'c777','Leader Jacket','199.99','67');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (11, 'c888','Sockets','9.5','1000');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (12, 'c999','Helmet','10.99','321');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (13, 'c101','Summer Skirt','12.99','33');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (14, 'c102','Summer Long Skirt','67.5','76');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (15, 'c103','Summer Shorts (red)','87.0','25');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (16, 'c104','Summer Shorts (blue)','99.0','5');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (17, 'c105','Summer Shorts (jean)','29.0','167');
INSERT INTO retailproduct(id, code, name, price, stock) VALUES (18, 'c106','Winter Leader Shorts','30.0','18');
ALTER SEQUENCE retailproduct_seq RESTART WITH 19;

INSERT INTO customer(id, name, email, phone, country) VALUES (1, 'Tristan Infinispan','tristisispan@quarkus.io','+39 666','Italy');
INSERT INTO customer(id, name, email, phone, country) VALUES (2, 'Gunnar Debezium','gmorling@quarkus.io','+49 128','Germany');
INSERT INTO customer(id, name, email, phone, country) VALUES (3, 'Raphael Jovial','rjovial@quarkus.io','+33 661','France');
INSERT INTO customer(id, name, email, phone, country) VALUES (4, 'Adeline Insolite','ainsolite@quarkus.io','+33 662','France');
INSERT INTO customer(id, name, email, phone, country) VALUES (5, 'William Fayot','wfayot@quarkus.io','+33 663','France');
INSERT INTO customer(id, name, email, phone, country) VALUES (6, 'Maria Rosario Frechilla','mfrechilla@quarkus.io','+34 221','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (7, 'Aurea Stork','amunoz@quarkus.io','+34 222','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (8, 'Denis Vigo','denis@quarkus.io','+34 223','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (9, 'Felix Manager','fmanager@quarkus.io','+34 224','Spain');
INSERT INTO customer(id, name, email, phone, country) VALUES (10, 'Igor Frere','ibrother@quarkus.io','+34 225','Spain');
ALTER SEQUENCE customer_seq RESTART WITH 11;